name: '532_project'
channels:
    - conda-forge
    - defaults
dependencies:
    - ipykernel=6.29.5
    - altair-all=5.5.0
    - dash=2.18.2
    - dash-bootstrap-components=1.7.1
    - plotly=6.0.0
    - tabulate=0.9.0  # df.to_markdown()
    - lxml=5.3.1  # pd.read_html()
    - pandas=2.2.3
    - numpy=2.2.3
    - pip=25.0.1
    - pip:
        - dash-vega-components==0.11.0
